/**
 * Interprets the complexity object from the LLM response
 * and returns human-readable grades + colors.
 */
export function gradeComplexity(complexity = {}) {
  const cc  = complexity.cyclomatic        ?? 0;
  const mi  = complexity.maintainability_index ?? 0;
  const mem = complexity.estimated_memory_kb   ?? 0;

  function ccGrade(v) {
    if (v <= 5)  return { label: "Simple",  color: "#39d353", bar: 20 };
    if (v <= 10) return { label: "Moderate", color: "#fbbf24", bar: 50 };
    if (v <= 20) return { label: "Complex",  color: "#f97316", bar: 75 };
    return             { label: "Risky",    color: "#ef4444", bar: 100 };
  }

  function miGrade(v) {
    if (v >= 80) return { label: "Excellent", color: "#39d353", bar: 100 };
    if (v >= 60) return { label: "Good",      color: "#22d3ee", bar: 75  };
    if (v >= 40) return { label: "Fair",      color: "#fbbf24", bar: 50  };
    return             { label: "Poor",      color: "#ef4444", bar: 25  };
  }

  function memGrade(v) {
    if (v < 64)   return { label: `~${v} KB`,    color: "#39d353" };
    if (v < 512)  return { label: `~${v} KB`,    color: "#22d3ee" };
    if (v < 2048) return { label: `~${Math.round(v/1024*10)/10} MB`, color: "#fbbf24" };
    return              { label: `~${Math.round(v/1024*10)/10} MB`, color: "#ef4444" };
  }

  return {
    cyclomatic:    { value: cc,  ...ccGrade(cc) },
    maintainability: { value: mi, ...miGrade(mi) },
    memory:        { value: mem, ...memGrade(mem) },
  };
}

/**
 * Wraps raw Java code in a full Maven project structure (string map).
 */
export function wrapInMaven(javaCode, className) {
  const pkg = "com.codebabel.generated";
  const dir = pkg.replace(/\./g, "/");
  return {
    [`pom.xml`]: `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>${pkg}</groupId>
  <artifactId>${className.toLowerCase()}</artifactId>
  <version>1.0.0</version>
  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.10.0</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>`,
    [`src/main/java/${dir}/${className}.java`]: `package ${pkg};\n\n${javaCode}`,
    [`src/test/java/${dir}/${className}Test.java`]: `package ${pkg};\n\nimport org.junit.jupiter.api.*;\nimport static org.junit.jupiter.api.Assertions.*;\n\n// Generated by CodeBabel Pro\npublic class ${className}Test {\n    // TODO: fill in test cases\n}\n`,
    [`README.md`]: `# ${className}\n\nGenerated by CodeBabel Pro from legacy source code.\n\n## Build\n\`\`\`bash\nmvn compile\nmvn test\n\`\`\`\n`,
  };
}
